update community set icon = '/assets/app/images/general/icons/community/kg/boxhill.png' where id in (select communityId from PreNursery where nameEn like '%Box Hill%');
update community set icon = '/assets/app/images/general/icons/community/kg/catiline.png' where id in (select communityId from PreNursery where nameEn like '%Catiline K%');
update community set icon = '/assets/app/images/general/icons/community/kg/cannan.png' where id in (select communityId from PreNursery where nameEn like 'Cannan %');
update community set icon = '/assets/app/images/general/icons/community/kg/creative.png' where id in (select communityId from PreNursery where nameEn like 'Creative%');
update community set icon = '/assets/app/images/general/icons/community/kg/elh.png' where id in (select communityId from PreNursery where nameEn like 'Excel London%');
update community set icon = '/assets/app/images/general/icons/community/kg/funful.png' where id in (select communityId from PreNursery where nameEn like '%Funful%');
update community set icon = '/assets/app/images/general/icons/community/kg/hkpresch.png' where id in (select communityId from PreNursery where nameEn like '%Ascot%');
update community set icon = '/assets/app/images/general/icons/community/kg/holytrinity.png' where id in (select communityId from PreNursery where nameEn like 'Holy Trinity%');
update community set icon = '/assets/app/images/general/icons/community/kg/kcis.png' where id in (select communityId from PreNursery where nameEn like 'Kiangsu%Non%');
update community set icon = '/assets/app/images/general/icons/community/kg/kclocal.png' where id in (select communityId from PreNursery where nameEn like 'Kiangsu%(Local%');
update community set icon = '/assets/app/images/general/icons/community/kg/keenmind.png' where id in (select communityId from PreNursery where nameEn like 'Keen Mind%');
update community set icon = '/assets/app/images/general/icons/community/kg/klcbchn.png' where id in (select communityId from PreNursery where nameEn like 'Kowloon City Baptist Church%');
update community set icon = '/assets/app/images/general/icons/community/kg/kllingliang.png' where id in (select communityId from PreNursery where nameEn like 'Kowloon Ling Liang%');
update community set icon = '/assets/app/images/general/icons/community/kg/learninghabitat.png' where id in (select communityId from PreNursery where nameEn like 'Learning Habitat%');
update community set icon = '/assets/app/images/general/icons/community/kg/ltlingliang.png' where id in (select communityId from PreNursery where nameEn like 'Lam Tin Ling Liang%');
update community set icon = '/assets/app/images/general/icons/community/kg/rhs.png' where id in (select communityId from PreNursery where nameEn like 'Rosar%');
update community set icon = '/assets/app/images/general/icons/community/kg/sjc.png' where id in (select communityId from PreNursery where nameEn like 'St Johannes%');
update community set icon = '/assets/app/images/general/icons/community/kg/spckg.png' where id in (select communityId from PreNursery where nameEn like 'HKSKH St Peter%');
update community set icon = '/assets/app/images/general/icons/community/kg/spn.png' where id in (select communityId from PreNursery where nameEn like '%Paul%s Day%');
update community set icon = '/assets/app/images/general/icons/community/kg/stcatherine.png' where id in (select communityId from PreNursery where nameEn like '%St Catherin%');
update community set icon = '/assets/app/images/general/icons/community/kg/think.png' where id in (select communityId from PreNursery where nameEn like '%Think%');
update community set icon = '/assets/app/images/general/icons/community/kg/tutortime.png' where id in (select communityId from PreNursery where nameEn like 'Tutor Time%');
update community set icon = '/assets/app/images/general/icons/community/kg/victoria.png' where id in (select communityId from PreNursery where nameEn like '%Victoria%');
update community set icon = '/assets/app/images/general/icons/community/kg/wisely.png' where id in (select communityId from PreNursery where nameEn like 'Wisely%');
update community set icon = '/assets/app/images/general/icons/community/kg/yanoitong.png' where id in (select communityId from PreNursery where nameEn like 'Yan O%');
update community set icon = '/assets/app/images/general/icons/community/kg/york.png' where id in (select communityId from PreNursery where nameEn like 'York English%');
update community set icon = '/assets/app/images/general/icons/community/kg/zenith.png' where id in (select communityId from PreNursery where nameEn like 'Zenith%');


update PreNursery set icon = '/assets/app/images/general/icons/community/kg/boxhill.png' where nameEn like '%Box Hill%';
update PreNursery set icon = '/assets/app/images/general/icons/community/kg/catiline.png' where nameEn like '%Catiline K%';
update PreNursery set icon = '/assets/app/images/general/icons/community/kg/cannan.png' where nameEn like '%Cannan %';
update PreNursery set icon = '/assets/app/images/general/icons/community/kg/creative.png' where nameEn like 'Creative%';
update PreNursery set icon = '/assets/app/images/general/icons/community/kg/elh.png' where nameEn like 'Excel London%';
update PreNursery set icon = '/assets/app/images/general/icons/community/kg/funful.png' where nameEn like '%Funful%';
update PreNursery set icon = '/assets/app/images/general/icons/community/kg/hkpresch.png' where nameEn like '%Ascot%';
update PreNursery set icon = '/assets/app/images/general/icons/community/kg/holytrinity.png' where nameEn like 'Holy Trinity%';
update PreNursery set icon = '/assets/app/images/general/icons/community/kg/kcis.png' where nameEn like 'Kiangsu%Non%';
update PreNursery set icon = '/assets/app/images/general/icons/community/kg/kclocal.png' where nameEn like 'Kiangsu%(Local%';
update PreNursery set icon = '/assets/app/images/general/icons/community/kg/keenmind.png' where nameEn like 'Keen Mind%';
update PreNursery set icon = '/assets/app/images/general/icons/community/kg/klcbchn.png' where nameEn like 'Kowloon City Baptist Church%';
update PreNursery set icon = '/assets/app/images/general/icons/community/kg/kllingliang.png' where nameEn like 'Kowloon Ling Liang%';
update PreNursery set icon = '/assets/app/images/general/icons/community/kg/learninghabitat.png' where nameEn like 'Learning Habitat%';
update PreNursery set icon = '/assets/app/images/general/icons/community/kg/ltlingliang.png' where nameEn like 'Lam Tin Ling Liang%';
update PreNursery set icon = '/assets/app/images/general/icons/community/kg/rhs.png' where nameEn like 'Rosar%';
update PreNursery set icon = '/assets/app/images/general/icons/community/kg/sjc.png' where nameEn like 'St Johannes%';
update PreNursery set icon = '/assets/app/images/general/icons/community/kg/spckg.png' where nameEn like 'HKSKH St Peter%';
update PreNursery set icon = '/assets/app/images/general/icons/community/kg/spn.png' where nameEn like '%Paul%s Day%';
update PreNursery set icon = '/assets/app/images/general/icons/community/kg/stcatherine.png' where nameEn like '%St Catherin%';
update PreNursery set icon = '/assets/app/images/general/icons/community/kg/think.png' where nameEn like '%Think%';
update PreNursery set icon = '/assets/app/images/general/icons/community/kg/tutortime.png' where nameEn like 'Tutor Time%';
update PreNursery set icon = '/assets/app/images/general/icons/community/kg/victoria.png' where nameEn like '%Victoria%';
update PreNursery set icon = '/assets/app/images/general/icons/community/kg/wisely.png' where nameEn like 'Wisely%';
update PreNursery set icon = '/assets/app/images/general/icons/community/kg/yanoitong.png' where nameEn like 'Yan O%';
update PreNursery set icon = '/assets/app/images/general/icons/community/kg/york.png' where nameEn like 'York English%';
update PreNursery set icon = '/assets/app/images/general/icons/community/kg/zenith.png' where nameEn like 'Zenith%';

update community set icon = '/assets/app/images/general/icons/community/kg/hklingliang.png' where id in (select communityId from Kindergarten where nameEn = 'Hong Kong Ling Liang Church Kindergarten');
update community set icon = '/assets/app/images/general/icons/community/kg/kentville.png' where id in (select communityId from Kindergarten where nameEn like 'Kentvi%');
update community set icon = '/assets/app/images/general/icons/community/kg/stcatherine.png' where id in (select communityId from Kindergarten where nameEn like '%St Catherin%');
update community set icon = '/assets/app/images/general/icons/community/kg/skh.png' where id in (select communityId from Kindergarten where nameEn = 'Sheng Kung Hui Kindergarten');
update community set icon = '/assets/app/images/general/icons/community/kg/spk.png' where id in (select communityId from Kindergarten where nameEn = 'St Paul''s Kindergarten');

update Kindergarten set icon = '/assets/app/images/general/icons/community/kg/boxhill.png' where nameEn like '%Box Hill%';
update Kindergarten set icon = '/assets/app/images/general/icons/community/kg/catiline.png' where nameEn like '%Catiline K%';
update Kindergarten set icon = '/assets/app/images/general/icons/community/kg/cannan.png' where nameEn like '%Cannan %';
update Kindergarten set icon = '/assets/app/images/general/icons/community/kg/creative.png' where nameEn like 'Creative%';
update Kindergarten set icon = '/assets/app/images/general/icons/community/kg/elh.png' where nameEn like 'Excel London%';
update Kindergarten set icon = '/assets/app/images/general/icons/community/kg/funful.png' where nameEn like '%Funful%';
update Kindergarten set icon = '/assets/app/images/general/icons/community/kg/hklingliang.png' where nameEn = 'Hong Kong Ling Liang Church Kindergarten';
update Kindergarten set icon = '/assets/app/images/general/icons/community/kg/hkpresch.png' where nameEn like '%Ascot%';
update Kindergarten set icon = '/assets/app/images/general/icons/community/kg/holytrinity.png' where nameEn like 'Holy Trinity%';
update Kindergarten set icon = '/assets/app/images/general/icons/community/kg/kentville.png' where nameEn like 'Kentvi%';
update Kindergarten set icon = '/assets/app/images/general/icons/community/kg/kcis.png' where nameEn like 'Kiangsu%Non%';
update Kindergarten set icon = '/assets/app/images/general/icons/community/kg/kclocal.png' where nameEn like 'Kiangsu%(Local%';
update Kindergarten set icon = '/assets/app/images/general/icons/community/kg/keenmind.png' where nameEn like 'Keen Mind%';
update Kindergarten set icon = '/assets/app/images/general/icons/community/kg/klcbchn.png' where nameEn like 'Kowloon City Baptist Church%';
update Kindergarten set icon = '/assets/app/images/general/icons/community/kg/kllingliang.png' where nameEn like 'Kowloon Ling Liang%';
update Kindergarten set icon = '/assets/app/images/general/icons/community/kg/learninghabitat.png' where nameEn like 'Learning Habitat%';
update Kindergarten set icon = '/assets/app/images/general/icons/community/kg/ltlingliang.png' where nameEn like 'Lam Tin Ling Liang%';
update Kindergarten set icon = '/assets/app/images/general/icons/community/kg/rhs.png' where nameEn like 'Rosar%';
update Kindergarten set icon = '/assets/app/images/general/icons/community/kg/sjc.png' where nameEn like 'St Johannes%';
update Kindergarten set icon = '/assets/app/images/general/icons/community/kg/skh.png' where nameEn = 'Sheng Kung Hui Kindergarten';
update Kindergarten set icon = '/assets/app/images/general/icons/community/kg/spckg.png' where nameEn like 'HKSKH St Peter%';
update Kindergarten set icon = '/assets/app/images/general/icons/community/kg/spk.png' where nameEn = 'St Paul''s Kindergarten';
update Kindergarten set icon = '/assets/app/images/general/icons/community/kg/spn.png' where nameEn like '%Paul%s Day%';
update Kindergarten set icon = '/assets/app/images/general/icons/community/kg/stcatherine.png' where nameEn like '%St Catherin%';
update Kindergarten set icon = '/assets/app/images/general/icons/community/kg/think.png' where nameEn like '%Think%';
update Kindergarten set icon = '/assets/app/images/general/icons/community/kg/tutortime.png' where nameEn like 'Tutor Time%';
update Kindergarten set icon = '/assets/app/images/general/icons/community/kg/victoria.png' where nameEn like '%Victoria%';
update Kindergarten set icon = '/assets/app/images/general/icons/community/kg/wisely.png' where nameEn like 'Wisely%';
update Kindergarten set icon = '/assets/app/images/general/icons/community/kg/yanoitong.png' where nameEn like 'Yan O%';
update Kindergarten set icon = '/assets/app/images/general/icons/community/kg/york.png' where nameEn like 'York English%';
update Kindergarten set icon = '/assets/app/images/general/icons/community/kg/zenith.png' where nameEn like 'Zenith%';



commit;