update community set icon = '/assets/app/images/general/icons/community/kg/boxhill.png' where id in (select communityId from PreNursery where nameEn like '%Box Hill%');
update community set icon = '/assets/app/images/general/icons/community/kg/catiline.jpg' where id in (select communityId from PreNursery where nameEn like '%Catiline K%');
update community set icon = '/assets/app/images/general/icons/community/kg/creative.jpg' where id in (select communityId from PreNursery where nameEn like 'Creative K%');
update community set icon = '/assets/app/images/general/icons/community/kg/elh.jpg' where id in (select communityId from PreNursery where nameEn like 'Excel London%');
update community set icon = '/assets/app/images/general/icons/community/kg/funful.jpg' where id in (select communityId from PreNursery where nameEn like '%Funful%');
update community set icon = '/assets/app/images/general/icons/community/kg/hkpresch.jpg' where id in (select communityId from PreNursery where nameEn like '%Ascot%');
update community set icon = '/assets/app/images/general/icons/community/kg/holytrinity.jpg' where id in (select communityId from PreNursery where nameEn like 'Holy Trinity%');
update community set icon = '/assets/app/images/general/icons/community/kg/keenmind.png' where id in (select communityId from PreNursery where nameEn like 'Keen Mind%');
update community set icon = '/assets/app/images/general/icons/community/kg/klcbchn.jpg' where id in (select communityId from PreNursery where nameEn like 'Kowloon City Baptist Church%');
update community set icon = '/assets/app/images/general/icons/community/kg/kllingliang.jpg' where id in (select communityId from PreNursery where nameEn like 'Kowloon Ling Liang%');
update community set icon = '/assets/app/images/general/icons/community/kg/learninghabitat.jpg' where id in (select communityId from PreNursery where nameEn like 'Learning Habitat%');
update community set icon = '/assets/app/images/general/icons/community/kg/ltlingliang.png' where id in (select communityId from PreNursery where nameEn like 'Lam Tin Ling Liang%');
update community set icon = '/assets/app/images/general/icons/community/kg/rhs.jpg' where id in (select communityId from PreNursery where nameEn like 'Rosar%');
update community set icon = '/assets/app/images/general/icons/community/kg/spckg.jpg' where id in (select communityId from PreNursery where nameEn like 'HKSKH St Peter%');
update community set icon = '/assets/app/images/general/icons/community/kg/spn.jpg' where id in (select communityId from PreNursery where nameEn like '%Paul%s Day%');
update community set icon = '/assets/app/images/general/icons/community/kg/stcatherine.jpg' where id in (select communityId from PreNursery where nameEn like '%St Catherin%');
update community set icon = '/assets/app/images/general/icons/community/kg/think.gif' where id in (select communityId from PreNursery where nameEn like '%Think%');
update community set icon = '/assets/app/images/general/icons/community/kg/victoria.jpg' where id in (select communityId from PreNursery where nameEn like '%Victoria%');
update community set icon = '/assets/app/images/general/icons/community/kg/wisely.jpg' where id in (select communityId from PreNursery where nameEn like 'Wisely%');
update community set icon = '/assets/app/images/general/icons/community/kg/yanoitong.jpg' where id in (select communityId from PreNursery where nameEn like 'Yan O%');
update community set icon = '/assets/app/images/general/icons/community/kg/york.jpg' where id in (select communityId from PreNursery where nameEn like 'York English%');


update PreNursery set icon = '/assets/app/images/general/icons/community/kg/boxhill.png' where nameEn like '%Box Hill%';
update PreNursery set icon = '/assets/app/images/general/icons/community/kg/catiline.jpg' where nameEn like '%Catiline K%';
update PreNursery set icon = '/assets/app/images/general/icons/community/kg/creative.jpg' where nameEn like 'Creative K%';
update PreNursery set icon = '/assets/app/images/general/icons/community/kg/elh.jpg' where nameEn like 'Excel London%';
update PreNursery set icon = '/assets/app/images/general/icons/community/kg/funful.jpg' where nameEn like '%Funful%';
update PreNursery set icon = '/assets/app/images/general/icons/community/kg/hkpresch.jpg' where nameEn like '%Ascot%';
update PreNursery set icon = '/assets/app/images/general/icons/community/kg/holytrinity.jpg' where nameEn like 'Holy Trinity%';
update PreNursery set icon = '/assets/app/images/general/icons/community/kg/keenmind.png' where nameEn like 'Keen Mind%';
update PreNursery set icon = '/assets/app/images/general/icons/community/kg/klcbchn.jpg' where nameEn like 'Kowloon City Baptist Church%';
update PreNursery set icon = '/assets/app/images/general/icons/community/kg/kllingliang.jpg' where nameEn like 'Kowloon Ling Liang%';
update PreNursery set icon = '/assets/app/images/general/icons/community/kg/learninghabitat.jpg' where nameEn like 'Learning Habitat%';
update PreNursery set icon = '/assets/app/images/general/icons/community/kg/ltlingliang.png' where nameEn like 'Lam Tin Ling Liang%';
update PreNursery set icon = '/assets/app/images/general/icons/community/kg/rhs.jpg' where nameEn like 'Rosar%';
update PreNursery set icon = '/assets/app/images/general/icons/community/kg/spckg.jpg' where nameEn like 'HKSKH St Peter%';
update PreNursery set icon = '/assets/app/images/general/icons/community/kg/spn.jpg' where nameEn like '%Paul%s Day%';
update PreNursery set icon = '/assets/app/images/general/icons/community/kg/stcatherine.jpg' where nameEn like '%St Catherin%';
update PreNursery set icon = '/assets/app/images/general/icons/community/kg/think.gif' where nameEn like '%Think%';
update PreNursery set icon = '/assets/app/images/general/icons/community/kg/victoria.jpg' where nameEn like '%Victoria%';
update PreNursery set icon = '/assets/app/images/general/icons/community/kg/wisely.jpg' where nameEn like 'Wisely%';
update PreNursery set icon = '/assets/app/images/general/icons/community/kg/yanoitong.jpg' where nameEn like 'Yan O%';
update PreNursery set icon = '/assets/app/images/general/icons/community/kg/york.jpg' where nameEn like 'York English%';

commit;