UPDATE PRENURSERY set applicationDateText='10月上網睇,11月1號開始Download Form' WHERE id=43 AND name='九龍靈糧堂幼兒園';
UPDATE PRENURSERY set applicationDateText='12月上網睇,1月開始報' WHERE id=205 AND name='劍鳴幼稚園';
UPDATE PRENURSERY set applicationDateText='3月1日, 2016' , applicationDate='2016-03-01' WHERE id=44 AND name='聖保祿幼兒園';
UPDATE PRENURSERY set applicationDateText='9月上網睇,1月開始報' WHERE id=148 AND name='基督教中心幼稚園';
UPDATE PRENURSERY set applicationDateText='8月上網睇,9月開始報' WHERE id=258 AND name='嘉德麗幼稚園';
UPDATE PRENURSERY set applicationDateText='冇指定日子, 依家可申請, 要mark 低申請2016/17年' WHERE id=466 AND name='約克英文小學暨幼稚園(九龍塘)';
UPDATE PRENURSERY set applicationDateText='3月17日, 2015' , applicationDate='2015-03-17' WHERE id=73 AND name='博士山(香港)國際幼稚園';
UPDATE PRENURSERY set applicationDateText='9月上網睇,11月7日拎Form' WHERE id=105 AND name='樂基幼兒學校(駿景園)';
UPDATE PRENURSERY set applicationDateText='夠1歲就可以報名' WHERE id=437 AND name='明雅國際幼兒學校';
UPDATE PRENURSERY set applicationDateText='12月上網睇,1月報名' WHERE id=195 AND name='香港聖公會青山聖彼得堂青雲路幼稚園';
UPDATE PRENURSERY set applicationDateText='夠1歲就報得' WHERE id=234 AND name='基督教香港信義會頌安幼兒學校';
UPDATE PRENURSERY set applicationDateText='8月29日 - 9月12日, 2015' , applicationDate='2015-08-29' WHERE id=282 AND name='綠茵英文(國際)幼稚園(常寧路)';
UPDATE PRENURSERY set applicationDateText='夠1歲半就可以報名,全年申請,有位就可以Interview' WHERE id=428 AND name='基督教宣道會沙田幼兒學校';